version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - PASSWORD=example
      - DB_NAME=expense
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      PASSWORD: example
      DB_NAME: expense
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
